### ISSUE TITLE
error when trying to register

### ISSUE THREAD

**Issue by dcp12345678** [kentcdodds/bookshelf#10]
When trying to register, after I click the register button I get this screen (using the codesandbox version):

A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.

Here are the stack frames, if that helps:
invokeGuardedCallbackDev
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:408:19
invokeGuardedCallback
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:454:31
beginWork$$1
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23217:7
performUnitOfWork
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22208:12
workLoopSync
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22185:22
renderRoot
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21878:11
runRootCallback
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21554:20
flushSyncCallbackQueueImpl/<
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11353:24
unstable_runWithPriority
https://o7xpx2q255.csb.app/node_modules/scheduler/cjs/scheduler.development.js:643:12
runWithPriority$2
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11305:10
flushSyncCallbackQueueImpl
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11349:7
flushSyncCallbackQueue
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11338:3
batchedEventUpdates$1
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21662:7
batchedEventUpdates
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:2348:12
dispatchEventForPluginEventSystem
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:5996:5
dispatchEvent
https://o7xpx2q255.csb.app/node_modules/react-dom/cjs/react-dom.development.js:6025:5

**Comment by kentcdodds** [comment]
Sorry, I can't provide support on this repo.

This appears to be a codesandbox issue though.
