### ISSUE TITLE
HMR Not working in Build an Epic React App workshop

### ISSUE THREAD

**Issue by jkmuka** [kentcdodds/bookshelf#100]
In exercise 1 noticed that HMR is not working. Using Chrome I can see HMR is waiting for updates but even a simple text change does not get picked up without refreshing the page. Also, this seems to only be an issue with this workshop. Other workshops and even a new CRA HMR seems to work fine

`[HMR] Waiting for update signal from WDS...`

**Comment by jkmuka** [comment]
FWIW, I setup a completely new CRA and manually added the exercises and HMR works fine there, just in the workshop setup it's not working

**Comment by kentcdodds** [comment]
Ok, thanks for the investigation @jkmuka!

**Comment by michaljuris** [comment]
Hot reloading doesn't work for me as well. I've just cloned the repo, checked out the _exercises/01-bootstrap_ branch (using _node go_) and simply modified the _index.exercise.js_ with the solution.

After the **first** file save, while an application is running in the browser, hot reload files _are downloaded_ , but the DOM is not modified:
![image](https://user-images.githubusercontent.com/391000/96632242-ba8e5e00-1317-11eb-88e9-0ebbdbaa758e.png)

Any other **consequent** file save is not reflected in the browser at all. The dev server rebuilds without an error each time though.

Tested in Chrome 87 (normal and incognito windows) and Safari 14.0
Node 12.18.3
Bookshelf app SHA - 65f7843 

index.exercise.js:
`import React from 'react'
import ReactDOM from 'react-dom'

import {Logo} from 'components/logo'
function App() {
  return (
    <>
      <Logo />
      <h1>Bookshelf</h1>
      <button onClick={e => console.log('Login')}>Login</button>
      <button onClick={e => console.log('Register')}>Registersss</button>
    </>
  )
}
ReactDOM.render(<App />, document.getElementById('root'))`

**Comment by kentcdodds** [comment]
Oh, one thing to keep in mind, Webpack doesn't like files being added/removed while it's running. So you need to make sure to restart the server each time you change the exercise. Is that the problem?

**Comment by michaljuris** [comment]
I've restarted the dev several times without changing the branch/exercise (actually the first thing I've tried ;) )

![Screen Recording 2020-10-20 at 21 14 08](https://user-images.githubusercontent.com/391000/96633612-a3e90680-1319-11eb-88b6-9b4bc8e29159.gif)

**Comment by kentcdodds** [comment]
Just tried on that first exercise and I was able to reproduce it. It looks like HMR starts working on exercise 3. So 1 and 2 it doesn't work. I'm not sure what the problem could be though 🙃

**Comment by michaljuris** [comment]
It's not a biggie for me. I was just curious if it is just me or not. Thx for looking into it!

**Comment by andresgallego** [comment]
Adding `FAST_REFRESH=false` to the `.env` file fixed the problem to me.

**Comment by kentcdodds** [comment]
Thank you for the working workaround @andresgallego! I've added that to both exercise 1 and 2 so people won't bump into this anymore.

I may actually end up adding that to every workshop/exercise because in the context of workshops fast refresh can often not be trusted...

Anyway, thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @andresgallego for ideas

**Comment by kentcdodds** [comment]
@all-contributors please add @michaljuris for bugs

**Comment by kentcdodds** [comment]
@all-contributors please add @jkmuka for bugs
