### ISSUE TITLE
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by 2456844450** [kentcdodds/bookshelf#104]
I get this error when I run 'node go'

![image](https://user-images.githubusercontent.com/52678998/97289211-da76d200-1881-11eb-8bc9-6155ce3c7898.png)

![image](https://user-images.githubusercontent.com/52678998/97289256-ea8eb180-1881-11eb-85ac-4f01d12d9c34.png)

**Comment by kentcdodds** [comment]
Hi @2456844450,

This issue and #103 are pretty odd. I'm not sure what could be the cause of these, but it does seem that there's something wrong with your computer's version of `git` or perhaps there was a problem when you cloned the repository. You might consider switching to the alternatives mentioned in the README:


> It's recommended you run everything locally in the same environment you work in every day, but if you're having issues getting things set up, you can also set this up using [GitHub Codespaces](https://github.com/features/codespaces) ([video demo](https://www.youtube.com/watch?v=gCoVJm3hGk4)) or [Codesandbox](https://codesandbox.io/s/github/kentcdodds/bookshelf).

Unfortunately I can't help you debug this any further 😬 Good luck!

**Comment by 2456844450** [comment]
ok,thank you.
