### ISSUE TITLE
About useAsync Hooks

### ISSUE THREAD

**Issue by Luncher** [kentcdodds/bookshelf#106]
Thank you for providing such good learning materials. I have a question for you, I hope you can answer for me

```typescript
function useSafeDispatch(dispatch) {
  const mounted = React.useRef(false)
  React.useLayoutEffect(() => {
    mounted.current = true
    return () => (mounted.current = false)
  }, [])
  return React.useCallback(
    (...args) => (mounted.current ? dispatch(...args) : void 0),
    [dispatch],
  )
}
```

Why do we need `useSafeDispatch` patch?
I know useLayoutEffect run after React has committed updates to the DOM，before the browser has a chance to paint.

** We are trying to prevent async task run before react commit update to the DOM？**

**Comment by kentcdodds** [comment]
Questions like this are best asked during https://kcd.im/office-hours

I'm not certain I understand your question. Please ask during office hours in the future :) Thanks!
