### ISSUE TITLE
Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering if debugger present

### ISSUE THREAD

**Issue by SangeetAgarwal** [kentcdodds/bookshelf#113]
Hello @kentcdodds,
I was stepping through the code & if I put a debugger in the `DiscoverBooksScreen`  then I get a "unstable_flushDiscreteUpdates..." warning.

Very curious why this happens, I had noticed exactly the same behavior in my app when I put a debugger in the component itself and searched frantically to see if I was doing something wrong but didn't see any literature on this. Any help/insight would be much appreciated. 

Again, thank you so much for putting this course together, I'm really enjoying it. 

![Untitled](https://user-images.githubusercontent.com/2169707/97792149-c815d480-1bb0-11eb-890c-c7c0e44ef32d.png)

![Untitled2](https://user-images.githubusercontent.com/2169707/97792174-10cd8d80-1bb1-11eb-8837-55045ca76c37.png)

**Comment by kentcdodds** [comment]
Hi @SangeetAgarwal,

I have no idea honestly 😅 if you can find a good way to reproduce this outside of the bookshelf app then it may be something to report to the react team (maybe even if you can't find a way to reproduce it outside the bookshelf app). As it is in afraid I don't have an answer for you. Good luck!

**Comment by SangeetAgarwal** [comment]
@kentcdodds  thanks for looking into this, what would be the best way of reporting this issue to the react team? perhaps open an issue @ https://github.com/facebook/react
I did [tweet ](https://twitter.com/SangyMohan/status/1322882578559442944) though not quite sure if that's the right approach.
Again, thank you

**Comment by kentcdodds** [comment]
Opening an issue is probably best

**Comment by SangeetAgarwal** [comment]
@kentcdodds opened an issue @ https://github.com/facebook/react/issues/20141 
I was able to reproduce this issue in an app written a couple of years back that used class components too.
Thanks, sorry to bother you on a Sunday but was very curious to know why this happens.

**Comment by SangeetAgarwal** [comment]
Hello @kentcdodds sorry to bother you again with this but doesn't seem https://github.com/facebook/react/issues/20141 is getting any attention. Anyway to get someone in the react team to look at this. Thanks

**Comment by kentcdodds** [comment]
Give them time. Is it urgent for you or are you just curious?

**Comment by SangeetAgarwal** [comment]
sure, no worries at all, don't want to bother them since I'm sure they got other urgent stuff happening.

> Is it urgent for you or are you just curious?

bit of both... so, I have an all hooks app in production that's doing fine, I plan on using the same pattern (swr, routing, authentication etc.) for another major app & for both these apps if I put a debugger & attempt to step through, I get this `unstable_flushDiscreteUpdates` warning. 

This second app I'm replatforming from ko will be used quite intensively & I just wanted to be sure I was doing something drastically wrong that may come to bite me later. 

Honestly, the fact that I had the same issue in your bookshelf app was bit of a relief, just meant it wasn't just me facing this problem.

And, yes, this  `unstable_flushDiscreteUpdates`  occurs _only_ if a debugger is present & I attempt to step through the code, so my guess is there isn't anything intrinsically wrong with the pattern I'm following, I think.

Thanks
