### ISSUE TITLE
Several videos with the same name cause unpredictable behavior

### ISSUE THREAD

**Issue by vasilii-kovalev** [kentcdodds/bookshelf#121]
In `Cache management` exercise there are 2 `Break Time` videos. It seems, that they have the same ids or something and behave incorrectly:
* you can be redirected to the second one after `Solution  8` video;
* uncompleted video is marked as `Completed`;
* they are both highlighted in the playlist and so on.

![image](https://user-images.githubusercontent.com/10310491/98099086-305e0200-1ea0-11eb-86d0-3b37c5dff917.png)
![image](https://user-images.githubusercontent.com/10310491/98099162-49ff4980-1ea0-11eb-954b-a793ed63b4dc.png)

**Comment by vasilii-kovalev** [comment]
Oh, and it is not possible to complete the second one:
![image](https://user-images.githubusercontent.com/10310491/98100044-6059d500-1ea1-11eb-8419-8a0c83a8d9f4.png)

**Comment by kentcdodds** [comment]
cc @dealingwith ☝️

**Comment by kentcdodds** [comment]
Reported 👍
