### ISSUE TITLE
Placeholder is displayed instead of actual video track sometimes

### ISSUE THREAD

**Issue by vasilii-kovalev** [kentcdodds/bookshelf#122]
It is not specific for this workshop, it occurred in previous ones as well.
In some cases when video starts, a placeholder is displayed instead of actual video track, though I can hear the audio one.
![image](https://user-images.githubusercontent.com/10310491/98106927-d9115f00-1eaa-11eb-8696-8ada7dfd98c5.png)
Only page refresh helps.

It happens rarely, but when it does, I can see such errors in console:
![image](https://user-images.githubusercontent.com/10310491/98107185-30afca80-1eab-11eb-9306-27355b39c00f.png)

**Comment by kentcdodds** [comment]
cc @dealingwith 👆

**Comment by kentcdodds** [comment]
Reported 👍 thanks!
