### ISSUE TITLE
suggest little change about useAsync hook

### ISSUE THREAD

**Issue by seanbruce** [kentcdodds/bookshelf#127]
I copy & paste useAsync hook in my side project that has TS setup. In the process of add TS types, I find two places where code could have little changes to better migrate to TS.
all of them is inside of `useSafeDispatch` function.
```
React.useLayoutEffect(() => {
  mounted.current = true;
  return () => (mounted.current = false) // A
}, []);
```
Refer React d.ts file here
```
// NOTE: callbacks are _only_ allowed to return either void, or a destructor.
// The destructor is itself only allowed to return void.
type EffectCallback = () => (void | (() => void | undefined));
```

I think maybe we could change line A to:
`return () => {mounted.current = false}`
in order to match useLayoutEffect API requirement and  remove TS error 

and also change 
```
return React.useCallback(
    (...args) => (mounted.current ? dispatch(...args) : void 0),
    [dispatch]
  );
```
to
```
return React.useCallback(
    (action) => (mounted.current ? dispatch(action) : void 0),
    [dispatch]
  );
```

due to dispatch TS type only accept one argument
```
// this technically does accept a second argument, but it's already under a deprecation warning
    // and it's not even released so probably better to not define it.
    type Dispatch<A> = (value: A) => void;
```

I'm just suggest those two changes here.  maybe helpful for someone also encounter the same TS error

**Comment by kentcdodds** [comment]
Hi @seanbruce,

Thanks for opening the issue. Because we're not using TypeScript I'm not going to make these changes, but hopefully your issue helps anyone else who's trying to migrate things to TypeScript for their own learning as well :)
