### ISSUE TITLE
Uncaught exception in Promise

### ISSUE THREAD

**Issue by westhouseit** [kentcdodds/bookshelf#13]
Hi Kent. Thanks for you helpful blog post and demo. Just wondering about resolving uncaught exceptions. For example in your demo click on the Login then Login without entering details: Uncaught (in promise) {status: 500, message: "Invalid username or password"}

If I catch an exception on e.g. login then I can't seem to get it to return/display the message. Is this perhaps to do with react-async processing?

Edit: Actually, a bit more checking and it looks like you just need to change Promise.reject to Promise.resolve in use-callback-status.js

**Comment by kentcdodds** [comment]
This should be fixed now. Thanks!
