### ISSUE TITLE
staleTime not work?

### ISSUE THREAD

**Issue by cxc421** [kentcdodds/bookshelf#134]
Hello @kentcdodds ,

In exercise 13 (render-as-you-fetch) extra credit, you set `staleTime` to 5 seconds to prevent react-query from making additional list-items requests.

https://github.com/kentcdodds/bookshelf/blob/83f5daa2578aef3828d9aa80ca46b382f4d4d9a0/src/context/auth-context.js#L17-L19

But when I do a force refresh on the [production deployment app](https://bookshelf.lol/), there are still additional list-item requests?

![image](https://user-images.githubusercontent.com/18439296/99209854-24a6ff80-27ff-11eb-893a-69496e40b7a6.png)

**Comment by kentcdodds** [comment]
Interesting. This could be a bug that popped up in react-query since I recorded the videos. I don't know when I'll have time to look into this, but if you learn what's going on then I'd welcome a pull request to fix it :) Thanks for brining it up!

**Comment by cxc421** [comment]
Hi @kentcdodds ,  I found that the closest "correct" version of react-query is actually **2.15.1**, and the change from **2.15.1** to **2.15.2** is seems like to solve the problems raised by the discussions you opened in the past: https://github.com/tannerlinsley/react-query/discussions/962  

I haven't read the entire discussion thread in detail, but maybe you have some other ideas on this issue?

I wrote a trivial example to demonstrate the problem:
https://codesandbox.io/s/staletime-issue-v2-2262-0wiyc?file=/src/App.js  (react-query@2.26.2)  
https://codesandbox.io/s/staletime-issue-v2-2151-bnugr?file=/src/App.js  (react-query@2.15.1)

**Comment by kentcdodds** [comment]
Could you open this as an issue on react-query?

**Comment by cxc421** [comment]
https://github.com/tannerlinsley/react-query/issues/1296

**Comment by kentcdodds** [comment]
I think react-query v3 will solve this for us. That'll be a bigger effort than this, so we'll lock as you suggest. Thanks!

@all-contributors please add @cxc421 for bugs
