### ISSUE TITLE
Question: useAsync method

### ISSUE THREAD

**Issue by ramyatrouny** [kentcdodds/bookshelf#140]
Do you mind to explain what does the useAsync method does? like more an example or valid verbose description 
Like literally I couldn't find any useful scenario to use this method.

**Comment by kentcdodds** [comment]
> Do you mind to explain what does the useAsync method does?

@ramyatrouny did you work through previous workshops? We built it together in the previous workshops. By the time you get to this one, you should have a clear understanding of the use case and how it works.

> Like literally I couldn't find any useful scenario to use this method.

Did you look at where it's used within the workshop? We have several exercises where you'll use it. Working through those exercises will do more to help you understand it's usefulness than any number of words I could write :)

Cheers!

**Comment by ramyatrouny** [comment]
Sorry in advance if it was misunderstood I didn't mean to be offensive
