### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by raqib-rasheed** [kentcdodds/bookshelf#144]
index.js:559 [MSW] Detected outdated Service Worker: Currently active Service Worker (d1e0e502f550d40a34bee90822e4bf98) is behind the latest published one (65d33ca82955e1c5928aed19d1bdf3f9).

The mocking is still enabled, but it's highly recommended that you update your Service Worker by running:

$ npx msw init <PUBLIC_DIR>

This is necessary to ensure that the Service Worker is in sync with the library to guarantee its stability.
If this message still persists after updating, please report an issue: https://github.com/open-draft/msw/issues

**Comment by kentcdodds** [comment]
Thanks for letting me know! I updated `msw` but forgot to check whether the service worker needed an update. Fixed now. Thanks!

@all-contributors please add @raqib-rasheed for bugs
