### ISSUE TITLE
Wait for the reload action to resolve? 

### ISSUE THREAD

**Issue by Andreeh** [kentcdodds/bookshelf#15]
Hi Kent! 

Thanks for an excellent repo and demo. I've learned a lot studying this. I have a question/issue regarding the login function. The login function will resolve before the getUser, or in your case the bootstrapAppData function, request is completed and resolved, causing a little lag where we cant show a loading spinner in the component awaiting the login function. Do you have any idea how to solve this since the reload action doesn't return a promise?

`const login = (credentials: any) =>
        authClient.login(credentials).then(reload);`

LoginForm.js
```
onSubmit={async ({ email, password }, actions) => {
    await login({ email, password });
    actions.setSubmitting(false); // will set to false before the reload action is finished
}}
```

**Comment by kentcdodds** [comment]
Hi @Andreeh 👋

I think the issue is that `reload` doesn't return a promise. You might want to file an issue on react-async.

I'm also considering changing from react-async to react-query for this project eventually.

Stay tuned for that :)
