### ISSUE TITLE
On the Integration testing exercise, comment is suggesting to mock `/me` endpoint rather than `/bootstrap`

### ISSUE THREAD

**Issue by payapula** [kentcdodds/bookshelf#173]
On the Exercise branch - exercises/13-integration-testing

The [comment](https://github.com/kentcdodds/bookshelf/blob/exercises/13-integration-testing/src/__tests__/book-screen.exercise.js) is suggesting to mock the old endpoint `/me` which has been actually replaced with `/bootstrap` endpoint in the previous modules. 

However in the video and final solutions, we are only mocking the `/bootstrap` endpoint to return {user, listItems}.  

<img width="900" alt="bookshelf" src="https://user-images.githubusercontent.com/7134153/111863375-3d781b00-8981-11eb-87b8-5e4a44ace3c1.png">

url ends with `/me`: respond with {user}
should be changed to
url ends with `/bootstrap`: respond with {user, listItems: []}

**Comment by kentcdodds** [comment]
Thanks @payapula! Fixed 👍

@all-contributors please add @payapula for docs
