### ISSUE TITLE
Instructions file missing.

### ISSUE THREAD

**Issue by Wgil** [kentcdodds/bookshelf#18]
Hello,

First of all thanks for uploading this repository which has been very helpful to me. I've been looking at it closely and I noticed the instructions are missing for the branch `exercises/app-state`. I'm not sure if this was intentional so I just wanted to let you know.

Thanks again.

**Comment by kentcdodds** [comment]
Hi @Wgil,

Sorry about that, I plan on doing a little work in this repository eventually to improve things. So look forward to that :)
