### ISSUE TITLE
Wrong description on epicreact.dev

### ISSUE THREAD

**Issue by PhilippVujic** [kentcdodds/bookshelf#239]
On the page https://epicreact.dev/modules/build-an-epic-react-app/build-an-epic-react-app-welcome the wrong description appears to me. Instead of the prerequisites and setup of bookshelf, it's showing the prerequisites and setup of react-fundamentals. 

Seems like everything except the transcript is not linked correctly.

**Comment by Mahendrareddy190** [comment]
can you explain more about what is not showing correctly

**Comment by kentcdodds** [comment]
I think it's been fixed.
