### ISSUE TITLE
Issue Chapter 8 Cache Management - listItems.find

### ISSUE THREAD

**Issue by renhyl** [kentcdodds/bookshelf#242]
Hi, I have run into js errors while following along with [epicreact.dev](https://epicreact.dev/) video chapter. Furthermore, comparing/copy over code from extra-1 files over, did appear to be broken as well. There seems to be an issue with client().then(data=> data.listItems), then() does not seem to do anything anymore.
/discover page has error: `There was an error: listItems.find is not a function`

I will re-visit this if I get the time and attempt to find problem and fix the issue.

**Comment by kentcdodds** [comment]
Hi @renhyl, would you mind joining for [office hours](https://kcd.im/office-hours) this week to go through this? I think it'd be much easier for us to understand each other on this issue if you can walk me through what you're doing.

**Comment by renhyl** [comment]
hi @kentcdodds , I will try to make it. Thanks a lot!

**Comment by kentcdodds** [comment]
Discussed here: https://www.youtube.com/watch?v=BT3LWn5q8z8

If you find the issue, please let us know.
