### ISSUE TITLE
not able  to run my local

### ISSUE THREAD

**Issue by Prashraj78** [kentcdodds/bookshelf#289]

**Comment by kentcdodds** [comment]
Hello @Prashraj78,

I'm afraid I don't know how to help you. The latest GitHub action is working which tests setup for linux, macOS, and windows. So if it's not working for you it's likely a problem with your own setup.

**Comment by kentcdodds** [comment]
I'm afraid I'm not able to do that. But you're welcome to ask on https://kcd.im/office-hours
