### ISSUE TITLE
Large applications ?

### ISSUE THREAD

**Issue by debianw** [kentcdodds/bookshelf#29]
Hi @kentcdodds , do you think this architecture could work for large applications ? any recommendation on how to organize hooks and components for large apps ?

You know in React is so hard to find a bullet proof recipe for big apps with ton of business logic, a recipe that scales and you don't loose control over the code.

**Comment by kentcdodds** [comment]
Hi @debianw,

I do. Though on a very large app I think a folder structure like this may make more sense: https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346

Good luck!~
