### ISSUE TITLE
Issues with the videos

### ISSUE THREAD

**Issue by pnadalini** [kentcdodds/bookshelf#318]
![image](https://github.com/user-attachments/assets/f8980b2c-3890-42d3-bba4-fa8c9f2cdf43)

There was a recent update to the site that caused a lot of exercises that I had completed to be mark as incomplete.

But the main issue is when working on the final part for "Build an Epic React" it seems like its showing the videos from other sections that probably had the same title.

You can see in the image the "Compount Components" and "Render as You Fetch" are marked as complete (even though i hadn't done them) and if you see the videos they're from other sections on the course

**Comment by kentcdodds** [comment]
We did a major overhaul of the site recently and there are a few bugs that still need squashing. Sorry for the trouble! I've let the team know about your report.
