### ISSUE TITLE
Possible Bug in exercises/03-data-fetching branch

### ISSUE THREAD

**Issue by nkabbara** [kentcdodds/bookshelf#34]
Hi Kent!

I think I've set everything up correctly. I'm seeing a service worker related error on the **03-data-fetching** branch (see image below), but not on master.

I wanted to bring it to your attention in case it's due to recent changes.

![mock-service-worker](https://user-images.githubusercontent.com/31865/79816842-c473dc00-8349-11ea-92e1-aad85379b983.png)

-Nash

**Comment by kentcdodds** [comment]
This was a bug. Thank you for reporting it. I've just pushed a fix :)

**Comment by nkabbara** [comment]
Awesome! Awesome!

FYI, for folks with vertical monitors, spoiler alert still spoils  😂

![vermon](https://user-images.githubusercontent.com/31865/79914147-62b77e80-83ea-11ea-855f-f01d7b508c3b.png)

**Comment by kentcdodds** [comment]
Ahaha! I'll move that further down 😆
