### ISSUE TITLE
Question: is useSafeDispatch still needed?

### ISSUE THREAD

**Issue by jelizarovas** [kentcdodds/bookshelf#41]
With the problem over at 

[https://github.com/tannerlinsley/react-query-devtools/issues/11](https://github.com/tannerlinsley/react-query-devtools/issues/11)

your solution was to use useSafeDispatch function.  but as [tannerlinsley ](https://github.com/tannerlinsley) noted

[> I've fixed this in React Query and release it. Do have any reason to believe that this issue was also present in the devtools itslef?](https://github.com/tannerlinsley/react-query-devtools/issues/11#issuecomment-600795378)

do you still need useSafeDispatch in [bookshelf/src/utils/use-async.js ](https://github.com/kentcdodds/bookshelf/blob/c3be72ec9fb01e19a996526c24f9039df85df2d6/src/utils/use-async.js#L3)?

**Comment by kentcdodds** [comment]
Yes, because I use `useAsync` for non-react-query code :)

https://github.com/kentcdodds/bookshelf/blob/c889fcd835ed62adbd85b246d184f29eef5944a1/src/context/auth-context.js#L30

Thanks :)

**Comment by FranciscoKloganB** [comment]
> Yes, because I use `useAsync` for non-react-query code :)
> 
> https://github.com/kentcdodds/bookshelf/blob/c889fcd835ed62adbd85b246d184f29eef5944a1/src/context/auth-context.js#L30
> 
> Thanks :)

Could you elaborate a little bit on the issue and how `useSafeDispatch` resolves it?

**Comment by kentcdodds** [comment]
Actually, it's no longer relevant. But it used to be helpful because React would give you a warning when setting state on a component that was unmounted.
