### ISSUE TITLE
On branch 05-routing `npm start` errs out

### ISSUE THREAD

**Issue by nkabbara** [kentcdodds/bookshelf#42]
Starting the server on this branch results in `Unexpected token 'export'`. To get it to work, I had to remove `src/setupProxy.js`.

I think this might be an issue for folks trying to solve the first exercise in this branch.

![err](https://user-images.githubusercontent.com/31865/80238780-a4cc0480-8624-11ea-9835-d40ec409c58e.png)

**Comment by kentcdodds** [comment]
Nice catch @nkabbara! Thank you very much for that 💯 I'm pushing a fix now :)
