### ISSUE TITLE
Possible bug in Branch 06-cache-management 

### ISSUE THREAD

**Issue by nkabbara** [kentcdodds/bookshelf#44]
Hi Kent!

I could be jumping the gun here as I haven't completed the extra credits, just skimmed them, but it looks like when I'm mutating state, the components aren't updating. See gif for example:

![v](https://user-images.githubusercontent.com/31865/80429322-73b43400-88b1-11ea-8e38-81846955d2e3.gif)

Is this expected with first exercise?

ps. Also running through a situation where I'm seeing infinite requests taking place after a mutation, but I haven't been able to reproduce yet.

**Comment by nkabbara** [comment]
Aha! I was conflating app state with server cache. After solving extra credit 6, it all made sense.

**Comment by kentcdodds** [comment]
Awesome! Hopefully *that* helped you learn more as well :) You learn more when you make assumptions and those are confirmed or corrected :)

**Comment by nkabbara** [comment]
💯
