### ISSUE TITLE
App does not run in Safari and Firefox

### ISSUE THREAD

**Issue by motdde** [kentcdodds/bookshelf#46]
error message: SyntaxError: Invalid regular expression: invalid group specifier name

The production app host here - https://bookshelf.lol/list gives the same error

**Comment by kentcdodds** [comment]
I tried this locally and unfortunately either I'm not familiar enough with the Firefox devtools, or they don't give much insight into where the error is actually happening. Even locally it just says there was a syntax error in the file, but doesn't say where. The file is huge (it's all the project dependencies) so I really have no idea which of all the dependencies this error could be in.

Maybe the next version of react-scripts (coming soon) will fix this, but right now I don't have the bandwidth to look into this :-(

**Comment by motdde** [comment]
Alright, Kent. Thanks for making this opensource I am learning a lot from it.

**Comment by kentcdodds** [comment]
Glad to hear it!

**Comment by wesbos** [comment]
Looks like the error is pointing to the first line, which is:

```
/*! For license information please see 2.e4f6d933.chunk.js.LICENSE.txt */
```

Maybe it's tripped up by `/*!`?

**Comment by kentcdodds** [comment]
Thanks Wes! Not sure how to test that theory 🙈

In Safari the error is: "SyntaxError: Invalid regular expression: invalid group specifier name" And it says the error is on line 2 which is the minification line where everything is 🙃

**Comment by wesbos** [comment]
Try build it without that license comment. I believe It's  a webpack setting that keeps comments that start with !

**Comment by kentcdodds** [comment]
Oh, I just removed the line in the built version of the file locally and that didn't make the error go away. Thanks though!

**Comment by wesbos** [comment]
Really weird - I've pinned it down to something in server.js -if you comment the imports in and our, you can see it work/not work. It's not consistent though

**Comment by wesbos** [comment]
If you take `import {setupWorker } from 'msw'` out of src/test/server.js, it runs.  That's all I have :)  haha really weird

**Comment by kentcdodds** [comment]
That's an enormous help Wes. Super thank you!

**Comment by awareness481** [comment]
Based on @wesbos findings I'm pretty sure I located the error.
On `{ setupWorker }` the file `getWorkerInstance.ts ` is imported which contains the following regex:

`/(?<!:)(\/*\.\/|\/{2,})/g`

The first group of the regex `(?<!:)` is a negative lookbehind which according to caniuse is not yet supported on Firefox & Safari. Hence the invalid group specifier name error

[caniuse -> regexp-lookbehind](https://caniuse.com/#feat=js-regexp-lookbehind)

@wesbos or @kentcdodds Do you want to go ahead and report the issue on [msw](https://github.com/mswjs/msw) as well?

**Comment by kentcdodds** [comment]
Thanks for the investigation everyone!

Cc @kettanaito

**Comment by kettanaito** [comment]
Hi. Thanks for finding this out! I've opened an issue in `msw` and will replace that negative lookbehind with a compatible replacement so you can run the app in Safari (Firefox) without issues.

**Comment by kentcdodds** [comment]
Big thank you to everyone in this thread 🤗

**Comment by kentcdodds** [comment]
@all-contributors please add @motdde for bugs

**Comment by kentcdodds** [comment]
@all-contributors please add @wesbos for ideas

**Comment by kentcdodds** [comment]
@all-contributors please add @awareness481 for ideas
