### ISSUE TITLE
What do you think about redirecting to a login route in case a protected route is accessed but user is not logged in?

### ISSUE THREAD

**Issue by vcardins** [kentcdodds/bookshelf#5]
What do you think about redirecting to a login route in case a protected route is accessed but user is not logged in?

**Comment by kentcdodds** [comment]
You can do that if you want, but then you probably want to redirect them back to the route they were trying to get to right? Seems like a lot of work to me. Why not just render the login form and leave them on that same route? That's what we do in this repo and that's on purpose :)
