### ISSUE TITLE
Profiler API

### ISSUE THREAD

**Issue by nkabbara** [kentcdodds/bookshelf#51]
Hi @kentcdodds 

In branch 09, the custom Profiler component api is expecting `metadata`, but around the app, `data` prop is being passed instead.

API: https://github.com/kentcdodds/bookshelf/blob/c6771628a6ec00e43648c9bfeaf338aff3889c04/src/components/profiler.extra-3.js#L20

Around app: https://github.com/kentcdodds/bookshelf/blob/c6771628a6ec00e43648c9bfeaf338aff3889c04/src/screens/book.extra-3.js#L28

-Nash

**Comment by kentcdodds** [comment]
Ah, thank you Nash! I'll get that fixed up.

**Comment by kentcdodds** [comment]
Pushed the fix just now. Thank you!
