### ISSUE TITLE
Remove import CSS in dev-tools and fix typos

### ISSUE THREAD

**Issue by hd4ng** [kentcdodds/bookshelf#54]
- I think you will not need `dev-tools.css` anymore since you're using emotion already
https://github.com/kentcdodds/bookshelf/blob/41ea6f361225140c840cd2703ca314fc635076e3/src/dev-tools/dev-tools.js#L9
- Typos: `enableDevToos` => 'enableDevTools'
https://github.com/kentcdodds/bookshelf/blob/41ea6f361225140c840cd2703ca314fc635076e3/src/dev-tools/dev-tools.js#L160

**Comment by kentcdodds** [comment]
Thanks!
