### ISSUE TITLE
Change error.code to error.status and ignore passwordHash in the return user object

### ISSUE THREAD

**Issue by hd4ng** [kentcdodds/bookshelf#55]
- I think it should change to `error.status` since you're using `error.status` everywhere (validateUser, authenticate, create, ...)
https://github.com/kentcdodds/bookshelf/blob/ea9422aa6c79efcc134857e85b17392d8bce268f/src/test/data/users.js#L27

- property `passwordHash` is in the return user object and I think this is not what you want. I saw you eliminate it in the read function
https://github.com/kentcdodds/bookshelf/blob/ea9422aa6c79efcc134857e85b17392d8bce268f/src/test/data/users.js#L42

**Comment by kentcdodds** [comment]
Fixed! Thank you!
