### ISSUE TITLE
Move basename prop from <Router> to <Routes>

### ISSUE THREAD

**Issue by hd4ng** [kentcdodds/bookshelf#56]
- Follow react router doc, the basename prop should be in the <Routes />: https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#move-basename-from-router-to-routes
https://github.com/kentcdodds/bookshelf/blob/ea9422aa6c79efcc134857e85b17392d8bce268f/src/context/index.js#L20

**Comment by kentcdodds** [comment]
Thanks! Fixed that!
