### ISSUE TITLE
Question: Why does discover page book list load multiple times?

### ISSUE THREAD

**Issue by JakeSchroeder** [kentcdodds/bookshelf#60]
Hello,

I added a console.log to print the books array in the discover page and when the app loads it calls the log 4 times in a row. I am wondering if this is by design or if there is some useEffect runaway. 

```
other stuff...

function DiscoverBooksScreen() {
  const [query, setQuery] = React.useState('')
  const [hasSearched, setHasSearched] = React.useState()
  const {books, error, isLoading, isError, isSuccess} = useBookSearch(query)

  console.log(books)

  React.useEffect(() => {
    return () => refetchBookSearchQuery()
  }, [])

...other stuff
```

![image](https://user-images.githubusercontent.com/18093452/82759898-19c66180-9dbe-11ea-92f0-7d655fa855ea.png)

**Comment by kentcdodds** [comment]
I don't think this happens anymore. Thanks!
