### ISSUE TITLE
Branch exercises/11-unit-testing - api-client.exercise.js TODO

### ISSUE THREAD

**Issue by zacjones93** [kentcdodds/bookshelf#70]
Hey Kent! In [/src/utils/__tests__/api-client.exercise.js](https://github.com/kentcdodds/bookshelf/blob/4a66b0d6ea2bab7e321db83bfbc25979b11051b4/src/utils/__tests__/api-client.exercise.js#L1), you have a `TODO: STOP, UPDATE THIS KENT` comment in the file.

There isn't much context as to what should be updated but I wanted to let you know that that was there as it could be confusing for learners.

**Comment by kentcdodds** [comment]
😂 that's hilarious. I can't remember off the top of my head, but I'll give it a look. Thanks @zacjones93!

**Comment by zacjones93** [comment]
If it helps, the tests that are written match what is present in this Section on EpicReact as far as I can tell

**Comment by kentcdodds** [comment]
Fixed! Thanks @zacjones93 :)
