### ISSUE TITLE
Error in "Context" section

### ISSUE THREAD

**Issue by komisz** [kentcdodds/bookshelf#89]
Issue:
Can not login into Bookshelf app "exercises/07-context".

Reproduction:
- register a new user
- use credentials to login 

- https://exercises-07-context.bookshelf.lol/ 
or
- locally: git clone - setup - npm start - node go -> context

![Screenshot 2020-10-13 at 19 18 40](https://user-images.githubusercontent.com/45998348/95894089-e8f4c200-0d88-11eb-8e71-63d08f22d96e.png)

Please let me know if I overlooked on something... Thanks in advance for your kind reply

**Comment by kentcdodds** [comment]
Hi @komisz! Thanks for letting me know. I've just pushed a fix. To get the update, run this:

```
git checkout exercises/07-context
git add -A
git reset --hard origin/exercises/07-context
```

That should get you fixed up.

@all-contributors please add @komisz for bugs

**Comment by kentcdodds** [comment]
@all-contributors please add @komisz for bug
