### ISSUE TITLE
useCallbackStatus usage

### ISSUE THREAD

**Issue by bogdansoare** [kentcdodds/bookshelf#9]
Hey @kentcdodds 👋 , first of all thank you for sharing this code, it really helped me discover a new way to structure my react apps.

One question that I have is why did you use the hook `useCallbackStatus`instead of just using `react-async` with a [`deferFn`](https://github.com/ghengeveld/react-async#deferfn) in the [login form](https://github.com/kentcdodds/bookshelf/blob/master/src/unauthenticated-app.js#L20) like [this](https://gist.github.com/bogdansoare/be69d723e0b09f520b5def2ea3ff3e77) ?

Thank you ❤️

**Comment by kentcdodds** [comment]
I honestly can't remember why I felt like I needed to build that. If it works, then feel free to use react-async instead :)
